version: "3.7"

services:
  aula_lab:
    image: postgres:13.4
    container_name: idw
    ports: 
      - 5432:5432 
    restart: always
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=contatos
    volumes: 
      - pgdata:/data/postgres

volumes: 
  pgdata:
    driver: local

